<center>
<h1> Biografi Singkat Presiden Susilo Bambang Yudhoyono </h1>
<hr>
</center>

<h4>Susilo Bambang Yudhoyono adalah presiden RI ke-6. Berbeda dengan presiden sebelumnya, beliau merupakan presiden pertama yang dipilih secara langsung oleh rakyat dalam proses Pemilu Presiden putaran II 20 September 2004. Lulusan terbaik AKABRI (1973) yang akrab disapa SBY ini lahir di Pacitan, Jawa Timur 9 September 1949. Istrinya bernama Kristiani Herawati, merupakan putri ketiga almarhum Jenderal (Purn) Sarwo Edhi Wibowo.<br>
<br>

Pensiunan jenderal berbintang empat ini adalah anak tunggal dari pasangan R. Soekotjo dan Sitti Habibah. Darah prajurit menurun dari ayahnya yang pensiun sebagai Letnan Satu. Sementara ibunya, Sitti Habibah, putri salah seorang pendiri Ponpes Tremas. Beliau dikaruniai dua orang putra yakni Agus Harimurti Yudhoyono (mengikuti dan menyamai jejak dan prestasi SBY, lulus dari Akmil tahun 2000 dengan meraih penghargaan Bintang Adhi Makayasa) dan Edhie Baskoro Yudhoyono (lulusan terbaik SMA Taruna Nusantara, Magelang yang kemudian menekuni ilmu ekonomi).<br>
<br>

Pendidikan SR adalah pijakan masa depan paling menentukan dalam diri SBY. Ketika duduk di bangku kelas lima, beliau untuk pertamakali kenal dan akrab dengan nama Akademi Militer Nasional (AMN), Magelang, Jawa Tengah. Di kemudian hari AMN berubah nama menjadi Akabri. SBY masuk SMP Negeri Pacitan, terletak di selatan alun-alun. Ini adalah sekolah idola bagi anak-anak Kota Pacitan. Mewarisi sikap ayahnya yang berdisiplin keras, SBY berjuang untuk mewujudkan cita-cita masa kecilnya menjadi tentara dengan masuk Akademi Angkatan Bersenjata Republik Indonesia (Akabri) setelah lulus SMA akhir tahun 1968. Namun, lantaran terlambat mendaftar, SBY tidak langsung masuk Akabri. Maka SBY pun sempat menjadi mahasiswa Teknik Mesin Institut 10 November Surabaya (ITS).<br>
<br>

Namun kemudian, SBY justru memilih masuk Pendidikan Guru Sekolah Lanjutan Pertama (PGSLP) di Malang, Jawa Timur. Sewaktu belajar di PGSLP Malang itu, beliau mempersiapkan diri untuk masuk Akabri. Tahun 1970, akhirnya masuk Akabri di Magelang, Jawa Tengah, setelah lulus ujian penerimaan akhir di Bandung. SBY satu angkatan dengan Agus Wirahadikusumah, Ryamizard Ryacudu, dan Prabowo Subianto. Semasa pendidikan, SBY yang mendapat julukan Jerapah, sangat menonjol. Terbukti, belaiu meraih predikat lulusan terbaik Akabri 1973 dengan menerima penghargaan lencana Adhi Makasaya.<br>
<br>

Pendidikan militernya dilanjutkan di Airborne and Ranger Course di Fort Benning, Georgia, AS (1976), Infantry Officer Advanced Course di Fort Benning, Georgia, AS (1982-1983) dengan meraih honor graduate, Jungle Warfare Training di Panama (1983), Anti Tank Weapon Course di Belgia dan Jerman (1984), Kursus Komandan Batalyon di Bandung (1985), Seskoad di Bandung (1988-1989) dan Command and General Staff College di Fort Leavenworth, Kansas, AS (1990-1991). Gelar MA diperoleh dari Webster University AS. Perjalanan karier militernya, dimulai dengan memangku jabatan sebagai Dan Tonpan Yonif Linud 330 Kostrad (Komandan Peleton III di Kompi Senapan A, Batalyon Infantri Lintas Udara 330/Tri Dharma, Kostrad) tahun 1974-1976, membawahi langsung sekitar 30 prajurit.<br>
<br>

Batalyon Linud 330 merupakan salah satu dari tiga batalyon di Brigade Infantri Lintas Udara 17 Kujang I/Kostrad, yang memiliki nama harum dalam berbagai operasi militer. Ketiga batalyon itu ialah Batalyon Infantri Lintas Udara 330/Tri Dharma, Batalyon Infantri Lintas Udara 328/Dirgahayu, dan Batalyon Infantri Lintas Udara 305/Tengkorak. Kefasihan berbahasa Inggris, membuatnya terpilih mengikuti pendidikan lintas udara (airborne) dan pendidikan pasukan komando (ranger) di Pusat Pendidikan Angkatan Darat Amerika Serikat, Ford Benning, Georgia, 1975. Kemudian sekembali ke tanah air, SBY memangku jabatan Komandan Peleton II Kompi A Batalyon Linud 305/Tengkorak (Dan Tonpan Yonif 305 Kostrad) tahun 1976-1977. Beliau pun memimpin Pleton ini bertempur di Timor Timur.<br>
<br>

Sepulang dari Timor Timur, SBY menjadi Komandan Peleton Mortir 81 Yonif Linud 330 Kostrad (1977). Setelah itu, beliau ditempatkan sebagai Pasi-2/Ops Mabrigif Linud 17 Kujang I Kostrad (1977-1978), Dan Kipan Yonif Linud 330 Kostrad (1979-1981), dan Paban Muda Sops SUAD (1981-1982). Ketika bertugas di Mabes TNI-AD, itu SBY kembali mendapat kesempatan sekolah ke Amerika Serikat. Dari tahun 1982 hingga 1983, beliau mengikuti Infantry Officer Advanced Course, Fort Benning, AS, 1982-1983 sekaligus praktek kerja-On the job training di 82-nd Airbone Division, Fort Bragg, AS, 1983. Kemudian mengikuti Jungle Warfare School, Panama, 1983 dan Antitank Weapon Course di Belgia dan Jerman, 1984, serta Kursus Komando Batalyon, 1985. Pada saat bersamaan SBY menjabat Komandan Sekolah Pelatih Infanteri (1983-1985)<br>
<br>

Lalu beliau dipercaya menjabat Dan Yonif 744 Dam IX/Udayana (1986-1988) dan Paban Madyalat Sops Dam IX/Udayana (1988), sebelum mengikuti pendidikan di Sekolah Staf dan Komando TNI-AD (Seskoad) di Bandung dan keluar sebagai lulusan terbaik Seskoad 1989. SBY pun sempat menjadi Dosen Seskoad (1989-1992), dan ditempatkan di Dinas Penerangan TNI-AD (Dispenad) dengan tugas antara lain membuat naskah pidato KSAD Jenderal Edi Sudradjat. Lalu ketika Edi Sudradjat menjabat Panglima ABRI, beliau ditarik ke Mabes ABRI untuk menjadi Koordinator Staf Pribadi (Korspri) Pangab Jenderal Edi Sudradjat (1993).<br>
<br>

Lalu, beliau kembali bertugas di satuan tempur, diangkat menjadi Komandan Brigade Infantri Lintas Udara (Dan Brigif Linud) 17 Kujang I/Kostrad (1993-1994) bersama dengan Letkol Riyamizard Ryacudu. Kemudian menjabat Asops Kodam Jaya (1994-1995) dan Danrem 072/Pamungkas Kodam IV/Diponegoro (1995). Tak lama kemudian, SBY dipercaya bertugas ke Bosnia Herzegovina untuk menjadi perwira PBB (1995). Beliau menjabat sebagai Kepala Pengamat Militer PBB (Chief Military Observer United Nation Protection Force) yang bertugas mengawasi genjatan senjata di bekas negara Yugoslavia berdasarkan kesepakatan Dayton, AS antara Serbia, Kroasia dan Bosnia Herzegovina. Setelah kembali dari Bosnia, beliau diangkat menjadi Kepala Staf Kodam Jaya (1996). Kemudian menjabat Pangdam II/Sriwijaya (1996-1997) sekaligus Ketua Bakorstanasda dan Ketua Fraksi ABRI MPR (Sidang Istimewa MPR 1998) sebelum menjabat Kepala Staf Teritorial (Kaster) ABRI (1998-1999).<br>
<br>

Sementara, langkah karir politiknya dimulai tanggal 27 Januari 2000, saat memutuskan untuk pensiun lebih dini dari militer ketika dipercaya menjabat sebagai Menteri Pertambangan dan Energi pada pemerintahan Presiden KH Abdurrahman Wahid. Tak lama kemudian, SBY pun terpaksa meninggalkan posisinya sebagai Mentamben karena Gus Dur memintanya menjabat Menkopolsoskam. Pada tanggal 10 Agustus 2001, Presiden Megawati mempercayai dan melantiknya menjadi Menko Polkam Kabinet Gotong-Royong. Tetapi pada 11 Maret 2004, beliau memilih mengundurkan diri dari jabatan Menko Polkam. Langkah pengunduran diri ini membuatnya lebih leluasa menjalankan hak politik yang akan mengantarkannya ke kursi puncak kepemimpinan nasional. Dan akhirnya, pada pemilu Presiden langsung putaran kedua 20 September 2004, SBY yang berpasangan dengan Jusuf Kalla meraih kepercayaan mayoritas rakyat Indonesia dengan perolehan suara di attas 60 persen. Dan pada tanggal 20 Oktober 2004 beliau dilantik menjadi Presiden RI ke-6.<br>
<br>
</h4>
